# Generated by Django 2.2.dev20181015224808 on 2018-10-16 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hearthstone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.CreateModel(
            name='CardUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hearthstone.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hearthstone.Card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hearthstone.Deck')),
            ],
        ),
    ]
