# Generated by Django 2.2.dev20181116091701 on 2018-11-16 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hearthstone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carduser',
            name='card',
        ),
        migrations.RemoveField(
            model_name='carduser',
            name='user',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(to='hearthstone.Card'),
        ),
        migrations.DeleteModel(
            name='CardDeck',
        ),
        migrations.DeleteModel(
            name='CardUser',
        ),
    ]
