# Generated by Django 2.2.dev20190107172653 on 2019-01-08 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hearthstone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hearthstone.Card')),
            ],
        ),
        migrations.CreateModel(
            name='CardsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hearthstone.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='carduser',
            name='card',
        ),
        migrations.RemoveField(
            model_name='carduser',
            name='user',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='profile',
            name='isFirstConnection',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='CardDeck',
        ),
        migrations.DeleteModel(
            name='CardUser',
        ),
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hearthstone.Topic'),
        ),
        migrations.AddField(
            model_name='cardsdeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hearthstone.Deck'),
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ManyToManyField(related_name='deck', through='hearthstone.CardsDeck', to='hearthstone.Deck'),
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ManyToManyField(related_name='cards', through='hearthstone.CardsUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
