# Generated by Django 2.2.dev20181116091701 on 2018-11-16 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0002_auto_20181116_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='owner',
            field=models.ManyToManyField(related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(related_name='decks', to='hearthstone.Card'),
        ),
    ]
