# Generated by Django 2.2.dev20190107152258 on 2019-01-07 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0003_auto_20181116_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isFirstConnection',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL),
        ),
    ]
