# Generated by Django 2.2.dev20190109180446 on 2019-01-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0004_auto_20190109_1729'),
        ('hearthstone', '0003_profile_elo'),
    ]

    operations = [
    ]
