# Generated by Django 2.2.dev20190109182037 on 2019-01-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0005_merge_20190109_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
