# Generated by Django 2.2.dev20190111144439 on 2019-01-12 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hearthstone', '0006_follow_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.AddField(
            model_name='game',
            name='opponent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='result',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
