# Generated by Django 2.2.dev20190111110410 on 2019-01-11 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hearthstone', '0006_follow_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_status', models.IntegerField(default=None)),
                ('user2_status', models.IntegerField(default=None)),
                ('exchange_status', models.IntegerField(default=None)),
                ('card1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_card1', to='hearthstone.Card')),
                ('card2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_card2', to='hearthstone.Card')),
                ('user1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_user1', to=settings.AUTH_USER_MODEL)),
                ('user2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
