# Generated by Django 2.2.dev20190111110410 on 2019-01-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0007_exchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='card1_id',
            new_name='card1',
        ),
        migrations.RenameField(
            model_name='exchange',
            old_name='card2_id',
            new_name='card2',
        ),
        migrations.RenameField(
            model_name='exchange',
            old_name='user1_id',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='exchange',
            old_name='user2_id',
            new_name='user2',
        ),
    ]
