# Generated by Django 2.2.dev20190111110410 on 2019-01-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0008_auto_20190111_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='exchange_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='user1_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='user2_status',
            field=models.IntegerField(),
        ),
    ]
