# Generated by Django 2.2.dev20190111110410 on 2019-01-11 16:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hearthstone', '0011_auto_20190111_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exchange',
            new_name='ExchangeCard',
        ),
    ]
