# Generated by Django 2.2.dev20190112161659 on 2019-01-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0007_auto_20190112_1048'),
        ('hearthstone', '0012_auto_20190111_1600'),
    ]

    operations = [
    ]
